/*
 * tiles.h - battleship tile art, palette and cursor sprite (data only)
 *
 * THE art-pass surface: every visual in the graphical renderer is defined
 * here — swap the arrays, keep the names, and no engine code changes.
 * Include from gfxcore.c ONLY (defines data, not just declarations).
 *
 * Format: one tile = 8x8 pixels x 4 bitplanes = 32 uint16_t words, plane 0
 * first, one word per row, leftmost pixel in bit 15 (pixels live in the
 * high byte since tiles are 8 wide). This is exactly struct Image data for
 * Width=8 Height=8 Depth=4 — see apps/pacmantests/c99-pac-man/Ghosts/.
 *
 * The placeholder art below is generated by the TILE_PAT() macro from a
 * 1-bit pattern plus foreground/background pen numbers. The art pass can
 * keep using TILE_PAT for 2-color tiles or replace any entry with a full
 * hand-authored (or tool-generated) 32-word multicolor array.
 *
 * See: contracts/amiga-adf-bootstrap.md, docs/plan-track1b-battleship.md
 */
#ifndef TILES_H
#define TILES_H

#include <stdint.h>
#include "cellmap.h"   /* TILE_* ids — tile_table[] is indexed by them */
#include "gfxcore.h"   /* PEN_* numbers the palette below gives color to */

/* ---- Palette (12-bit RGB4, LoadRGB4 order, indexed by PEN_*) ---- */

static const uint16_t tile_palette[16] = {
    0x000, 0xFFF, 0x05A, 0xD22, 0x2C4, 0xFC3, 0x888, 0x038,
    0xF80, 0x0DE, 0x000, 0x000, 0x000, 0x000, 0x000, 0x000
};

/* ---- 2-color tile composer ---- */

/* One row of one plane: fg pens where the pattern bit is set, bg pens
 * elsewhere; shifted into the high byte (8-wide tile in a 16-bit word). */
#define TROW(pat, fg, bg, pl) \
    ((uint16_t)(((((fg) >> (pl)) & 1) ? (uint8_t)(pat) : 0) | \
                ((((bg) >> (pl)) & 1) ? (uint8_t)~(uint8_t)(pat) : 0)) << 8)

#define TPLANE(pl, fg, bg, r0, r1, r2, r3, r4, r5, r6, r7) \
    TROW(r0, fg, bg, pl), TROW(r1, fg, bg, pl), \
    TROW(r2, fg, bg, pl), TROW(r3, fg, bg, pl), \
    TROW(r4, fg, bg, pl), TROW(r5, fg, bg, pl), \
    TROW(r6, fg, bg, pl), TROW(r7, fg, bg, pl)

#define TILE_PAT(fg, bg, r0, r1, r2, r3, r4, r5, r6, r7)  { \
    TPLANE(0, fg, bg, r0, r1, r2, r3, r4, r5, r6, r7),      \
    TPLANE(1, fg, bg, r0, r1, r2, r3, r4, r5, r6, r7),      \
    TPLANE(2, fg, bg, r0, r1, r2, r3, r4, r5, r6, r7),      \
    TPLANE(3, fg, bg, r0, r1, r2, r3, r4, r5, r6, r7) }

/* ---- Placeholder tiles ---- */

static const uint16_t tile_blank[32] = TILE_PAT(PEN_BG, PEN_BG,
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00); /* 00000000 */

static const uint16_t tile_sea[32] = TILE_PAT(PEN_SEA_DK, PEN_SEA,
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x04,  /* 00000100 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x20,  /* 00100000 */
    0x00,  /* 00000000 */
    0x00); /* 00000000 */

static const uint16_t tile_miss[32] = TILE_PAT(PEN_TEXT, PEN_SEA,
    0x00,  /* 00000000 */
    0x3C,  /* 00111100 */
    0x42,  /* 01000010 */
    0x42,  /* 01000010 */
    0x42,  /* 01000010 */
    0x3C,  /* 00111100 */
    0x00,  /* 00000000 */
    0x00); /* 00000000 */

static const uint16_t tile_hit[32] = TILE_PAT(PEN_HIT, PEN_SEA,
    0x81,  /* 10000001 */
    0x42,  /* 01000010 */
    0x24,  /* 00100100 */
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0x24,  /* 00100100 */
    0x42,  /* 01000010 */
    0x81); /* 10000001 */

static const uint16_t tile_hit2[32] = TILE_PAT(PEN_TEXT, PEN_SEA,
    0x81,  /* 10000001 */
    0x42,  /* 01000010 */
    0x24,  /* 00100100 */
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0x24,  /* 00100100 */
    0x42,  /* 01000010 */
    0x81); /* 10000001 */

static const uint16_t tile_legend_hit[32] = TILE_PAT(PEN_HIT, PEN_BG,
    0x81,  /* 10000001 */
    0x42,  /* 01000010 */
    0x24,  /* 00100100 */
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0x24,  /* 00100100 */
    0x42,  /* 01000010 */
    0x81); /* 10000001 */

static const uint16_t tile_ship_bow_h[32] = TILE_PAT(PEN_SHIP, PEN_SEA,
    0x00,  /* 00000000 */
    0x3F,  /* 00111111 */
    0x7F,  /* 01111111 */
    0xFF,  /* 11111111 */
    0xFF,  /* 11111111 */
    0x7F,  /* 01111111 */
    0x3F,  /* 00111111 */
    0x00); /* 00000000 */

static const uint16_t tile_ship_mid_h[32] = TILE_PAT(PEN_SHIP, PEN_SEA,
    0x00,  /* 00000000 */
    0xFF,  /* 11111111 */
    0xFF,  /* 11111111 */
    0xFF,  /* 11111111 */
    0xFF,  /* 11111111 */
    0xFF,  /* 11111111 */
    0xFF,  /* 11111111 */
    0x00); /* 00000000 */

static const uint16_t tile_ship_stern_h[32] = TILE_PAT(PEN_SHIP, PEN_SEA,
    0x00,  /* 00000000 */
    0xFC,  /* 11111100 */
    0xFE,  /* 11111110 */
    0xFF,  /* 11111111 */
    0xFF,  /* 11111111 */
    0xFE,  /* 11111110 */
    0xFC,  /* 11111100 */
    0x00); /* 00000000 */

static const uint16_t tile_ship_bow_v[32] = TILE_PAT(PEN_SHIP, PEN_SEA,
    0x18,  /* 00011000 */
    0x3C,  /* 00111100 */
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x7E); /* 01111110 */

static const uint16_t tile_ship_mid_v[32] = TILE_PAT(PEN_SHIP, PEN_SEA,
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x7E); /* 01111110 */

static const uint16_t tile_ship_stern_v[32] = TILE_PAT(PEN_SHIP, PEN_SEA,
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x3C,  /* 00111100 */
    0x18); /* 00011000 */

/* Attack animation: expanding blast, then dissipating ring. */
static const uint16_t tile_anim_0[32] = TILE_PAT(PEN_EXPL, PEN_SEA,
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00); /* 00000000 */

static const uint16_t tile_anim_1[32] = TILE_PAT(PEN_EXPL, PEN_SEA,
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x3C,  /* 00111100 */
    0x3C,  /* 00111100 */
    0x3C,  /* 00111100 */
    0x3C,  /* 00111100 */
    0x00,  /* 00000000 */
    0x00); /* 00000000 */

static const uint16_t tile_anim_2[32] = TILE_PAT(PEN_EXPL, PEN_SEA,
    0x00,  /* 00000000 */
    0x3C,  /* 00111100 */
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x7E,  /* 01111110 */
    0x3C,  /* 00111100 */
    0x00); /* 00000000 */

static const uint16_t tile_anim_3[32] = TILE_PAT(PEN_EXPL, PEN_SEA,
    0x3C,  /* 00111100 */
    0x7E,  /* 01111110 */
    0xFF,  /* 11111111 */
    0xFF,  /* 11111111 */
    0xFF,  /* 11111111 */
    0xFF,  /* 11111111 */
    0x7E,  /* 01111110 */
    0x3C); /* 00111100 */

static const uint16_t tile_anim_4[32] = TILE_PAT(PEN_EXPL, PEN_SEA,
    0xE7,  /* 11100111 */
    0xC3,  /* 11000011 */
    0x81,  /* 10000001 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x81,  /* 10000001 */
    0xC3,  /* 11000011 */
    0xE7); /* 11100111 */

static const uint16_t tile_anim_5[32] = TILE_PAT(PEN_EXPL, PEN_SEA,
    0x81,  /* 10000001 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x81); /* 10000001 */

static const uint16_t tile_border_h[32] = TILE_PAT(PEN_TEXT, PEN_BG,
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0xFF,  /* 11111111 */
    0xFF,  /* 11111111 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00); /* 00000000 */

static const uint16_t tile_border_v[32] = TILE_PAT(PEN_TEXT, PEN_BG,
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0x18); /* 00011000 */

static const uint16_t tile_box_tl[32] = TILE_PAT(PEN_TEXT, PEN_BG,
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x1F,  /* 00011111 */
    0x1F,  /* 00011111 */
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0x18); /* 00011000 */

static const uint16_t tile_box_tr[32] = TILE_PAT(PEN_TEXT, PEN_BG,
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0xF8,  /* 11111000 */
    0xF8,  /* 11111000 */
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0x18); /* 00011000 */

static const uint16_t tile_box_bl[32] = TILE_PAT(PEN_TEXT, PEN_BG,
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0x1F,  /* 00011111 */
    0x1F,  /* 00011111 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00); /* 00000000 */

static const uint16_t tile_box_br[32] = TILE_PAT(PEN_TEXT, PEN_BG,
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0xF8,  /* 11111000 */
    0xF8,  /* 11111000 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00); /* 00000000 */

static const uint16_t tile_line[32] = TILE_PAT(PEN_DIM, PEN_BG,
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0xFF,  /* 11111111 */
    0xFF,  /* 11111111 */
    0x00,  /* 00000000 */
    0x00,  /* 00000000 */
    0x00); /* 00000000 */

static const uint16_t tile_endgame_bar[32] = TILE_PAT(PEN_DIM, PEN_BG,
    0x00,  /* 00000000 */
    0xFF,  /* 11111111 */
    0xFF,  /* 11111111 */
    0xFF,  /* 11111111 */
    0xFF,  /* 11111111 */
    0xFF,  /* 11111111 */
    0xFF,  /* 11111111 */
    0x00); /* 00000000 */

static const uint16_t tile_clock[32] = TILE_PAT(PEN_TEXT, PEN_BG,
    0x3C,  /* 00111100 */
    0x42,  /* 01000010 */
    0x99,  /* 10011001 */
    0xBD,  /* 10111101 */
    0x85,  /* 10000101 */
    0x81,  /* 10000001 */
    0x42,  /* 01000010 */
    0x3C); /* 00111100 */

static const uint16_t tile_conn_on[32] = TILE_PAT(PEN_CONN, PEN_BG,
    0x18,  /* 00011000 */
    0x3C,  /* 00111100 */
    0x7E,  /* 01111110 */
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0x7E,  /* 01111110 */
    0x3C,  /* 00111100 */
    0x18); /* 00011000 */

static const uint16_t tile_conn_off[32] = TILE_PAT(PEN_DIM, PEN_BG,
    0x18,  /* 00011000 */
    0x3C,  /* 00111100 */
    0x7E,  /* 01111110 */
    0x18,  /* 00011000 */
    0x18,  /* 00011000 */
    0x7E,  /* 01111110 */
    0x3C,  /* 00111100 */
    0x18); /* 00011000 */

/* ---- Tile table (indexed by the TILE_* enum in cellmap.h) ---- */

static const uint16_t *tile_table[TILE_COUNT] = {
    tile_blank,        /* TILE_BLANK        */
    tile_sea,          /* TILE_SEA          */
    tile_miss,         /* TILE_MISS         */
    tile_hit,          /* TILE_HIT          */
    tile_hit2,         /* TILE_HIT2         */
    tile_legend_hit,   /* TILE_LEGEND_HIT   */
    tile_ship_bow_h,   /* TILE_SHIP_BOW_H   */
    tile_ship_mid_h,   /* TILE_SHIP_MID_H   */
    tile_ship_stern_h, /* TILE_SHIP_STERN_H */
    tile_ship_bow_v,   /* TILE_SHIP_BOW_V   */
    tile_ship_mid_v,   /* TILE_SHIP_MID_V   */
    tile_ship_stern_v, /* TILE_SHIP_STERN_V */
    tile_anim_0,       /* TILE_ANIM_0       */
    tile_anim_1,       /* TILE_ANIM_1       */
    tile_anim_2,       /* TILE_ANIM_2       */
    tile_anim_3,       /* TILE_ANIM_3       */
    tile_anim_4,       /* TILE_ANIM_4       */
    tile_anim_5,       /* TILE_ANIM_5       */
    tile_border_h,     /* TILE_BORDER_H     */
    tile_border_v,     /* TILE_BORDER_V     */
    tile_box_tl,       /* TILE_BOX_TL       */
    tile_box_tr,       /* TILE_BOX_TR       */
    tile_box_bl,       /* TILE_BOX_BL       */
    tile_box_br,       /* TILE_BOX_BR       */
    tile_line,         /* TILE_LINE         */
    tile_endgame_bar,  /* TILE_ENDGAME_BAR  */
    tile_clock,        /* TILE_CLOCK        */
    tile_conn_on,      /* TILE_CONN_ON      */
    tile_conn_off,     /* TILE_CONN_OFF     */
};

/* ---- Attack cursor (hardware sprite 2, colors from registers 21-23) ----
 *
 * 16-wide sprite, corner brackets in the left 8 columns (the Atari
 * cursor_pmg pattern). Two images for the blink: image 0 uses sprite
 * plane A only (color 21), image 1 plane B only (color 22). Layout is
 * SimpleSprite data: posctl pair, height x (planeA, planeB), terminator. */

#define CURSOR_SPR_HEIGHT 8
#define CURSOR_SPR_WORDS  (2 + CURSOR_SPR_HEIGHT * 2 + 2)

static const uint16_t cursor_spr_a[CURSOR_SPR_WORDS] = {
    0x0000, 0x0000,
    0xF000, 0x0000,
    0x9000, 0x0000,
    0x9000, 0x0000,
    0x0000, 0x0000,
    0x0000, 0x0000,
    0x9000, 0x0000,
    0x9000, 0x0000,
    0xF000, 0x0000,
    0x0000, 0x0000
};

static const uint16_t cursor_spr_b[CURSOR_SPR_WORDS] = {
    0x0000, 0x0000,
    0x0000, 0xF000,
    0x0000, 0x9000,
    0x0000, 0x9000,
    0x0000, 0x0000,
    0x0000, 0x0000,
    0x0000, 0x9000,
    0x0000, 0x9000,
    0x0000, 0xF000,
    0x0000, 0x0000
};

/* Sprite color registers 21-23 (sprites 2/3 bank): bright / blink / mix. */
static const uint16_t cursor_spr_rgb[3] = { 0xFFF, 0xFC3, 0xF80 };

#endif /* TILES_H */
